- name: variables from play-1
  hosts: localhost
  vars_files:
    variables.yaml
  tasks: 
  - name: check variable
    ansible.builtin.debug:
      msg: "Hi, Iam learning {{course}}, trainer is {{trainer}}, Duration is {{Duration}}"