- name: checking data types
  hosts: localhost
  vars:
    NAME: SivaKumar
    Skills: 
    - Devops
    - Shell
    - Ansible
    - Linux
    Experience: # Experience is map type. It contain key value pairs
      Devops: 7
      Ansible: 4
      linux: 3
    Trainer: true
  tasks:
  - name: print key value pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"

  - name: print list
    ansible.builtin.debug:
      msg: "Skills: {{Skills}}"

  - name: print map
    ansible.builtin.debug:
      msg: "Experience: {{Experience}}"

  - name: print boolean
    ansible.builtin.debug:
      msg: "is he trainer: {{Trainer}}"